spring:
  application:
    name: solva-task
  datasource:
    hikari:
      schema: solva
    username: postgres
    password: user
    url: jdbc:postgresql://localhost:5432/todo
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
  servlet:
    context-path: /api
  client:
    url: https://date.nager.at/api/v3/publicholidays/{year}/{countryCode}
